/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */

val springBootVersion by extra { "1.5.14.RELEASE" }
extra["reactor.version"] = "3.1.0.RELEASE"

the<DependencyManagementExtension>().apply {
    imports {
        mavenBom("org.springframework.boot:spring-boot-starter-parent:$springBootVersion")
    }
}