/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */

val springBootVersion by extra { "2.1.7.RELEASE" }
val reactorVersion by extra {"3.2.12.RELEASE"}
val jUnitJupiterVersion by extra {"5.5.2"}
val assertJVersion by extra {"3.8.0"}
val jUnitPlatformVersion by extra {"1.5.2"}

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:2.1.7.RELEASE")
    }
}

version = 1.0

tasks.named<Test>("test") {
    useJUnitPlatform()
}

plugins {
    java
    id("org.springframework.boot") version "2.1.7.RELEASE"
    id("io.spring.dependency-management") version "1.0.8.RELEASE"
}

dependencyManagement {
    imports {
        mavenBom("org.springframework.boot:spring-boot-starter:$springBootVersion")
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter:$springBootVersion")
    implementation("org.springframework.boot:spring-boot-starter-thymeleaf:$springBootVersion")
    implementation("org.springframework.boot:spring-boot-starter-web:$springBootVersion")
    testImplementation("org.springframework.boot:spring-boot-starter-test:$springBootVersion")
    testImplementation("org.junit.jupiter:junit-jupiter-api:$jUnitJupiterVersion")
    testImplementation("org.assertj:assertj-core:$assertJVersion")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:$jUnitJupiterVersion")
    testRuntimeOnly("org.junit.platform:junit-platform-engine:$jUnitPlatformVersion")
    //implementation("io.projectreactor:reactor-core:$reactorVersion")
}